LabExercise1/LabExercise1/urls.py
from django.contrib import admin
from django.urls import path
from hybe import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('',views.index, name='index'),
    path('logout', views.signout, name='signout'),
    path('newuser',views.newuser, name='newuser'),
    path('',views.signin, name='signin'),
    path('show',views.show, name='show'),
    path('display',views.display, name='display'),
    path('addnew',views.addnew, name='addnew'),
    path('edit/<int:id>',views.edit, name='edit'),
    path('update/<int:id>',views.update, name='update'),
    path('delete/<int:id>',views.destroy, name='destroy'),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
  

LabExercise1/hybe/models.py
from django.db import models

# Create your models here.
# Create your models here.
class Artist(models.Model):  
    img = models.FileField()
    birthname = models.CharField(max_length=100)  
    stagename = models.CharField(max_length=100)
    birthdate = models.DateField()
    age = models.IntegerField()
    
   
    class Meta:  
        db_table = "tblartists"

LabExercise1/hybe/forms.py
from django import forms  
from hybe.models import Artist  
class ArtistForm(forms.ModelForm):  
    class Meta:  
        model = Artist 
        fields = ['img', 'birthname', 'stagename', 'birthdate', 'age'] 
        widgets = { 'img': forms.ClearableFileInput(attrs={ 'class': 'form-control' }),
            'birthname': forms.TextInput(attrs={ 'class': 'form-control' }), 
            'stagename': forms.TextInput(attrs={ 'class': 'form-control' }), 
            'birthdate': forms.DateInput(attrs={ 'class': 'form-control', 'type': 'date' }), 
            'age': forms.TextInput(attrs={ 'class': 'form-control' }),
      }

LabExercise1/hybe/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout
from django.shortcuts import HttpResponseRedirect
from hybe.functions import handle_uploaded_file
from hybe.forms import ArtistForm
from hybe.models import Artist

# Create your views here.
def index(request): 
    return render(request, 'welcome.html')

def newuser(request):
    if request.method == 'POST':
        print("post");
        form = UserCreationForm(request.POST)
        if form.is_valid():
            print("valid");
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/')
        else:
            print(form.errors)
            return render(request, 'signup.html', {'form': form})
    else:
        form = UserCreationForm()
        return render(request, 'signup.html', {'form': form})

def signin(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/display') #profile
        else:
            msg = 'Error Login'
            form = AuthenticationForm(request.POST)
            return render(request, 'login.html', {'form': form, 'msg': msg})
    else:
        form = AuthenticationForm()
        return render(request, 'login.html', {'form': form})

def signout(request):
    logout(request)
    return redirect('/')

@login_required
def addnew(request):
    if request.method == "POST":
        form = ArtistForm(request.POST, request.FILES)
        print("Before form validation")
        if form.is_valid():
            try:
                handle_uploaded_file(request.FILES['img'])
                model_instance = form.save(commit=False)
                model_instance.save()
                return redirect('/show')
            except:
                pass
        else:
            print("Form is not valid")
            print(form.errors)
    else:
        form = ArtistForm()
    return render(request,"add.html",{'form':form})

@login_required
def show(request):
    artists = Artist.objects.all()
    return render(request,"read.html", {'artists':artists})

@login_required
def display(request):
    images = Artist.objects.all()
    return render(request,"gallery.html", {'images':images})

@login_required
def edit(request, id):  
    artist = Artist.objects.get(id=id)  
    return render(request,'edit.html', {'artist':artist})

@login_required
def update(request, id):  
    artist = Artist.objects.get(id=id)  
    form = ArtistForm(request.POST, instance = artist)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'artist': artist})

def destroy(request, id):  
    artist = Artist.objects.get(id=id)  
    artist.delete()  
    return redirect("/show")  

LabExercise1/hybe/templates/add.html
{% extends "base.html" %}
  
{% block title %}Add New Artist{% endblock title %}
  
{% block content %}
<nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: black;"">
    <div class="container-fluid justify-content">
      <a class="navbar-brand" style="color:#ffff00" href="#">HYBE</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" style="color:#ffff00" href="/display">Gallery</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" style="color:#ffff00" href="/show">List of Artists</a>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link ms-auto" style="color:#ffff00" href="logout">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

<div class="col-md-12">    
    <form method="POST" enctype="multipart/form-data" class="post-form" action="/addnew">  
    {% csrf_token %}   
        <div class="container-crud" style="margin-top:100px">  
            <div class="col-12">  
            <h3>Enter Artist Details</h3>  
            </div>    
         
            <div class="mb-3"> 
                <label class="crud-label">Image:</label>  
                {{ form.img }}   
            </div> 
            
            <div class="mb-3"> 
                <label class="crud-label">Birth Name:</label>  
                {{ form.birthname }}   
            </div>  
            <div class="mb-3"> 
                <label class="crud-label">Stage Name:</label>  
                {{ form.stagename }}   
            </div>
            <div class="mb-3"> 
                <label class="crud-label">Birth Date:</label>  
                {{ form.birthdate }}   
            </div>
            <div class="mb-3"> 
                <label class="crud-label">Age:</label>  
                {{ form.age }}   
            </div>
            <div class="mb-3"> 
                <button type="submit" class="btn btn-primary" style="margin:0 -0.5rem;">Submit</button>   
            </div>
            <div class="mb-3"> 
                    <button type="" class="btn btn-danger" style="margin:-0.5rem 0;"><a href="/show">Cancel</a></button>  
            </div>
        </div>   
    </form>  
</div> 
{% endblock content %} 

LabExercise1/hybe/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>{% block title %}HYBE{% endblock %}</title>
  {% load static %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.0/css/jquery.dataTables.min.css" />
  <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    * {
      margin: 0;
      padding: 0;
      font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
    }

    body {
      height: 100vh;
      display: flex;
      background-image: url('{% static "image/HYBE.jpeg" %}');
      background-size: cover;
      background-repeat: no-repeat;
      background-attachment: fixed;
    }

    .container {
      margin:auto;
      background: transparent;
      border: 1.5px solid rgba(255, 255, 0, 0.2);
      padding: 1rem;
      width: 350px;
      height: 400px;
      border-radius: 6px;
      backdrop-filter: blur(20px);
    }
    .container-crud {
      margin:auto;
      background: transparent;
      border: 1.5px solid rgba(255, 255, 0, 0.2);
      padding: 2.5rem;
      width: 450px;
      height: 600px;
      border-radius: 6px;
      backdrop-filter: blur(20px);
    }

    .container-edit {
      margin:auto;
      background: transparent;
      border: 1.5px solid rgba(255, 255, 0, 0.2);
      padding: 2.5rem;
      width: 800px;
      height: 800px;
      border-radius: 6px;
      backdrop-filter: blur(20px);
    }

    .container-img {
      margin:auto;
      background: transparent;
      border: 1.5px solid rgba(255, 255, 0, 0.2);
      padding: 2.5rem;
      width: 950px;
      height: 100%;
      border-radius: 6px;
      backdrop-filter: blur(20px);
    }

    form {
      margin: 1rem 1.5rem;
      text-align: center;
      color: #fff;
    }

    .input {
      width: 100%;
      height: 2.25rem;
      margin: 2rem 0 0 0;
      position: relative;
    }

    .input input {
      width: 100%;
      height: 100%;
      border-radius: 1.5rem;
      padding: 0 1rem;
      box-sizing: border-box;
      outline: none;
      font-weight: 600;
      background: transparent;
      border: 1px solid #000;
      color: #fff;
    }

    .floating-label {
      font-size: 13px;
      position: absolute;
      top: 45%;
      left: 1rem;
      color: #fff;
      transform: translateY(-50%);
      pointer-events: none;
      padding: 0 0.25rem;
      transition: 0.3s ease all;
    }

    .input span {
      position: absolute;
      top: 50%;
      transform: translateY(-50%);
      right: 1rem;
      color: #fff;
      font-size: 1.25rem;
    }

    .input input:focus+.floating-label,
    .input input:not(:placeholder-shown)+.floating-label {
      top: -12px;
      left: .5rem;
      font-size: 11px;
    }
    

    a {
      text-decoration: none;
      color: #FFFF00;
    }

    a:hover{
      color:rgba(255,255,0,0.5);
    }

    button {
      width: 80%;
      height: 2.25rem;
      margin: 1rem 0;
      border-radius: 1rem;
      border: none;
      padding: 0.5rem 0;
      font-size: 1rem;
      font-weight: 500;
      line-height: 1;
      cursor: pointer;
      background: #ffff00;
      filter: drop-shadow(0 0 4px #333);
    }

    .btn-primary{
      background: #ffff00;
      color:#000;
      border-color: #FFFF00;
    }

    .btn-primary:hover{
      background-color: rgba(255,255,0,0.8);
      border-color: rgba(255,255,0,0.8);
      color:grey;
    }

    .btn-danger{
      background: black;
      color:#ffff00;
      border-color: black;
    }

    .register-link {
      font-size: 14px;
    }

    h1, h2, h3{
      color:#FFFF00;
    }

    table{
      width:100%;
    }

    table, th, td{
      color: #fff;
      text-align: center;
      vertical-align: middle;
    }

    img{
      width:200px;
      height:300px;
      margin: 5px;
      transition: transform 0.3s ease-in-out;
    }

    img:hover{
      transform: scale(1.1);
    }

    .navbar {
    position: fixed; /* Fixed position */
    top: 0; /* Stick to the top of the viewport */
    left: 0; /* Stick to the left side of the viewport */
    right: 0; /* Stick to the right side of the viewport */
    z-index: 1000; /* Adjust the z-index as needed */
    background-color: #333; /* Set background color */
    padding: 10px 0; /* Add padding as needed */
    /* Add other styles such as text color, font-size, etc. */
}

.crud-label{
  color:black;
  display:block;
  float:left;
}


  </style>
</head>

<body>
  
  <div style="margin:auto;">

    {% load static %}
    <main>
      {% block content %}
      {% endblock %}
    </main>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdn.datatables.net/1.12.0/js/jquery.dataTables.min.js"></script>
  <script>
    $(document).ready(function () {
      $('#bootstrapdatatable').DataTable({
        "aLengthMenu": [[3, 5, 10, 25, -1], [3, 5, 10, 25, "All"]],
        "iDisplayLength": 3
      }
      );
    });
  </script>
</body>

</html>

LabExercise1/hybe/templates/edit.html
{% extends "base.html" %}

{% block title %}Edit Artist Information{% endblock title %}

{% block content %}
<nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: black;"">
    <div class="container-fluid justify-content">
      <a class="navbar-brand" style="color:#ffff00" href="#">HYBE</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" style="color:#ffff00" href="/display">Gallery</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" style="color:#ffff00" href="/show">List of Artists</a>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link ms-auto" style="color:#ffff00" href="logout">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<div class="col-md-12">
    <form method="POST" enctype="multipart/form-data" class="post-form" action="/update/{{ artist.id }}">
        {% csrf_token %}
        <div class="container-edit" style="margin-top:100px">
            <div class="col-12">  
            <h3>Update Details</h3>  
            </div>  
            <div class="row">
                <!-- First Column -->
                <div class="mb-3">
                    {% if artist.img %}
                        <img src="{{ artist.img.url }}" class="tbl-img" alt="Image Here" style="display:block; margin:auto; padding: 10px 10px;">
                    {% endif %}
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="" class="crud-label">Profile</label>
                        <input type="file" class="form-control" name="img" id="id_img" accept="image/*" />
                    </div>
                    <div class="mb-3">
                        <label class="crud-label">Birth Name:</label>
                        <input type="text" class="form-control" name="birthname" id="id_birthname" required maxlength="100" value="{{ artist.birthname }}" />
                    </div>
                    <div class="mb-3">
                        <label class="crud-label">Stage Name:</label>
                        <input type="text" class="form-control" name="stagename" id="id_stagename" required maxlength="100" value="{{ artist.stagename }}" />
                    </div>
                </div>
                <!-- Second Column -->
                <div class="col-md-6">
                    <div class="mb-3">
                        <label class="crud-label">Birth Date:</label>
                        <input type="date" class="form-control" name="birthdate" id="id_birthdate" value="{{ artist.birthdate|date:'Y-m-d' }}" />
                    </div>
                    <div class="mb-3">
                        <label class="crud-label">Age:</label>
                        <input type="text" class="form-control" name="age" id="id_age" value="{{ artist.age }}" />
                    </div>
                </div>
            </div>
            <center><div style="padding-top: 20px;">
                <div class="col-md-6">
                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary" style="margin:0 -0.5rem;">Update</button>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <button type="" class="btn btn-danger" style="margin:-0.5rem 0;"><a href="/show">Cancel</a></button>
                    </div>
                </div>
            </div></center>
        </div>
    </form>
</div>
{% endblock content %}

LabExercise1/hybe/templates/gallery.html
{% extends "base.html" %}
  
{% block title %}Gallery{% endblock title %}
  
{% block content %}
<nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: black;"">
  <div class="container-fluid justify-content">
    <a class="navbar-brand" style="color:#ffff00" href="#">HYBE</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" style="color:#ffff00" href="/display">Gallery</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style="color:#ffff00" href="/show">List of Artists</a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link ms-auto" style="color:#ffff00" href="logout">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

 <div style="margin:auto;">
        <div class="container-img" style="margin-top:100px">
          <div class="col-12">  
            <center><h2 style="font-weight:bold; margin-bottom: 20px;">Artists Photos</h2> </center> 
            </div> 
            
            {% for image in images %} 
              <img src="{{ image.img.url }}" class="img-gallery">
            {% endfor %} 
            </div>  
    </div>
{% endblock content %}

LabExercise1/hybe/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container">
    <form method="post">
        <h1>Login</h1> {{ msg }}
        
        <div class="input">
            {% csrf_token %}
            <!-- Username Field -->
            <div class="input">
                <input type="text" name="username" id="id_username" placeholder=""required>
                <label for="{{ form.username.id_for_label }}" class="floating-label">
                    {{ form.username.label_tag }}</label>
                    <span class="material-icons">person</span>   
            </div>

            <!-- Password Field -->
            <div class="input">
                <input type="password" name="password" id="id_password" placeholder="" required>
                <label for="{{ form.password.id_for_label }}" class="floating-label">
                    {{ form.password.label_tag }}
                </label>
                <span class="material-icons">lock</span>
            </div>
            <button type="submit" style="margin-top: 50px;">Login</button>
            <p class=".register-link">No account? <a href=/newuser>Sign up</a></p>
        </div>
    </form>
</div>
{% endblock %}

LabExercise1/hybe/templates/read.html
{% extends "base.html" %}
  
{% block title %}List of Artists{% endblock title %}

{% block content %}
<nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: black;"">
    <div class="container-fluid justify-content">
      <a class="navbar-brand" style="color:#ffff00" href="#">HYBE</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" style="color:#ffff00" href="/display">Gallery</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" style="color:#ffff00" href="/show">List of Artists</a>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link ms-auto" style="color:#ffff00" href="logout">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
 <div class="col-md-12 content" style="margin-top:100px">
        <span><a href="/addnew" class="btn btn-primary" style="margin-bottom: 30px;">Add New Artist</a></span>
        <div class="table-responsive" style="background-color: transparent; backdrop-filter: blur(20px); padding:20px;">
            <table id="bootstrapdatatable" class="table table-striped">
            <thead>
                <th>#</th>
                <th>Profile</th>
                <th>Birth Name</th>
                <th>Stage Name</th>
                <th>Birth Date</th>
                <th>Age</th>
                <th>Edit</th>
                <th>Delete</th>
            </thead>
            <tbody>
            {% for artist in artists %}  
                <tr>  
                <td>{{ forloop.counter }}</td>
                {% if artist.img %}
                    <td>
                        <img src="{{ artist.img.url }}" class="tbl-img">
                    </td>  
                {% endif %}
                <td>{{ artist.birthname }}</td>
                <td>{{ artist.stagename }}</td>
                <td>{{ artist.birthdate }}</td> 
                <td>{{ artist.age }}</td> 
                <td><a href="/edit/{{ artist.id }}" class="btn btn-primary">Edit</a></td>
                <td><a href="/delete/{{ artist.id }}" class="btn btn-danger">Delete</a></td>  
                </tr>  
            {% endfor %} 
            </tbody>
            </table>
            </div>  
    </div>
{% endblock content %}

LabExercise1/hybe/templates/signup.html
{% extends 'base.html' %}

{% block title %}Signup{% endblock %}

{% block content %}
<div class="container">
  <form method="POST">
    <h2>Sign up</h2>
    {% csrf_token %}
    <!-- Username Field -->
    <div class="input">
      <input type="text" name="username" id="id_username" placeholder=""required>
      <label for="{{ form.username.id_for_label }}" class="floating-label">{{ form.username.label_tag }}</label><br>
    </div>

    <!-- Password Field -->
    <div class="input">
      <input type="password" name="password1" id="id_password1" placeholder="" required>
      <label for="{{ form.password1.id_for_label }}" class="floating-label">{{ form.password1.label_tag }}</label><br>
    </div>

    <!-- Confirm Password Field -->
    <div class="input">
      <input type="password" name="password2" id="id_password2" placeholder="" required>
      <label for="{{ form.password2.id_for_label }}" class="floating-label">{{ form.password2.label_tag }}</label><br>
    </div>
    {{ field }}
    {% for error in field.errors %}
    <p style="color: red">{{ error }}</p>
    {% endfor %}
    </p>
    <button type="submit">Sign up</button>
    <p class=".register-link">Already have an account? <a href="/">Login</a></p>
  </form>
</div>
{% endblock %}

LabExercise1/hybe/templates/welcome.html
{% extends 'base.html' %}
  
{% block title %}Login{% endblock %}
  
{% block content %}
   <h2>Welcome!</h2>
   {% if user.is_authenticated %}
      <script>
        window.location.href = "{% url 'show' %}";
     </script>
    {% else %}
      <a href="signin" class="btn btn-primary"><span class="glyphicon glyphicon-log-in"></span>Login</a> 
      <a href="signup" class="btn btn-success">Signup</a>
    {% endif %}
{% endblock %}